In [1]:
import pandas as pd
import numpy as np
import os

os.chdir('../')
import data 
os.chdir('notebooks')

2023-01-23 15:27:14.842809: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
def read_data(path):
    df = pd.read_csv(path, parse_dates = ['timestamp'])

    #Clean dataset
    df.columns = [strip_accents(col) for col in df.columns]
    stations = df.columns[df.columns.str.contains("\(")]
    df = df.groupby('timestamp')[stations].sum()
    df = df[df.index <= pd.Timestamp('2021-04-30 23:45:00')]
    return df

In [ ]:
transactions_fpath = '../../data/clean_transactions.csv'
df = read_data(transactions_fpath)
df.to_parquet('../../data/transactions.parquet')

In [ ]:
os.path.getsize('../../data/transactions.parquet')/1000000

In [ ]:
df.to_parquet('../../data/transactions.parquet')

In [ ]:
os.path.getsize('../../data/transactions.parquet')/1000000

In [ ]:
stations = pd.read_csv('../../data/clean_stations_database_v2.csv')

In [ ]:
stations.to_parquet('../../data/stations_DB.parquet')

# Transforming outputs

In [ ]:
# Small Decimals
df = pd.read_parquet("../outputs/transformers_results_v1.parquet")
df.to_parquet('../../data/exp_1.parquet')
os.path.getsize('../../data/exp_1.parquet')/1000000

In [ ]:
# Transforming to Real Values
df = pd.read_parquet("../outputs/transformers_results_v1.parquet")
mean = 188.4318877714359
variance = 120971.63484231419
df = (df * np.sqrt(variance)) + mean
df.to_parquet('../../data/exp_2.parquet')
os.path.getsize('../../data/exp_2.parquet')/1000000

In [ ]:
# Aproximate to Closest Integer
df = pd.read_parquet("../outputs/transformers_results_v1.parquet")
mean = 188.4318877714359
variance = 120971.63484231419
df = (df * np.sqrt(variance)) + mean
df = df.round(decimals = 0)
df.to_parquet('../outputs/exp_1_2023_01_18.parquet')
os.path.getsize('../outputs/exp_1_2023_01_18.parquet')/1000000

In [ ]:
# Aproximate to Closest Integer
df = pd.read_parquet("../outputs/transformers_results_v2.parquet")
mean = 188.4318877714359
variance = 120971.63484231419
df = (df * np.sqrt(variance)) + mean
df = df.round(decimals = 0)
df.to_parquet('../outputs/exp2_2023_01_20.parquet')
os.path.getsize('../outputs/exp2_2023_01_20.parquet')/1000000

In [27]:
df = pd.read_parquet('../outputs/predictions_small_expt1.parquet')

In [30]:
df.head(50)

(02000) cabecera autopista norte  \
timestamp                                               
2015-08-15 04:00:00                             383.0   
2015-08-15 04:15:00                             390.0   
2015-08-15 04:30:00                             408.0   
2015-08-15 04:45:00                             457.0   
2015-08-15 05:00:00                             528.0   
2015-08-15 05:15:00                             629.0   
2015-08-15 05:30:00                             763.0   
2015-08-15 05:45:00                             881.0   
2015-08-15 06:00:00                            1108.0   
2015-08-15 06:15:00                            1275.0   
2015-08-15 06:30:00                            1389.0   
2015-08-15 06:45:00                            1514.0   
2015-08-15 07:00:00                            1656.0   
2015-08-15 07:15:00                            1781.0   
2015-08-15 07:30:00                            1804.0   
2015-08-15 07:45:00                            1694.0   
2015-08-15 08:00:00                            1664.0   
2015-08-15 08:15:00                            1637.0   
2015-08-15 08:30:00                            1550.0   
2015-08-15 08:45:00                            1375.0   
2015-08-15 09:00:00                            1289.0   
2015-08-15 09:15:00                            1194.0   
2015-08-15 09:30:00                            1125.0   
2015-08-15 09:45:00                            1063.0   
2015-08-15 10:00:00                             998.0   
2015-08-15 10:15:00                             952.0   
2015-08-15 10:30:00                             876.0   
2015-08-15 10:45:00                             851.0   
2015-08-15 11:00:00                             825.0   
2015-08-15 11:15:00                             801.0   
2015-08-15 11:30:00                             777.0   
2015-08-15 11:45:00                             743.0   
2015-08-15 12:00:00                             729.0   
2015-08-15 12:15:00                             744.0   
2015-08-15 12:30:00                             713.0   
2015-08-15 12:45:00                             757.0   
2015-08-15 13:00:00                             749.0   
2015-08-15 13:15:00                             818.0   
2015-08-15 13:30:00                             819.0   
2015-08-15 13:45:00                             839.0   
2015-08-15 14:00:00                             893.0   
2015-08-15 14:15:00                             947.0   
2015-08-15 14:30:00                             965.0   
2015-08-15 14:45:00                             997.0   
2015-08-15 15:00:00                            1016.0   
2015-08-15 15:15:00                            1064.0   
2015-08-15 15:30:00                            1094.0   
2015-08-15 15:45:00                            1106.0   
2015-08-15 16:00:00                            1133.0   
2015-08-15 16:15:00                            1168.0   

                     (02001) centro comercial santa fe  (02101) toberin  \
timestamp                                                                 
2015-08-15 04:00:00                               86.0             86.0   
2015-08-15 04:15:00                               89.0             89.0   
2015-08-15 04:30:00                               93.0             92.0   
2015-08-15 04:45:00                               97.0             97.0   
2015-08-15 05:00:00                              101.0            102.0   
2015-08-15 05:15:00                              105.0            110.0   
2015-08-15 05:30:00                              110.0            120.0   
2015-08-15 05:45:00                              112.0            129.0   
2015-08-15 06:00:00                              114.0            147.0   
2015-08-15 06:15:00                              116.0            177.0   
2015-08-15 06:30:00                              117.0            200.0   
2015-08-15 06:45:00                              119.0            228.0   
2015-0

In [22]:
df

(02000) cabecera autopista norte  \
timestamp                                               
2015-08-15 04:00:00                             254.0   
2015-08-15 04:15:00                             254.0   
2015-08-15 04:30:00                             254.0   
2015-08-15 04:45:00                             255.0   
2015-08-15 05:00:00                             255.0   
...                                               ...   
2015-08-20 16:45:00                             257.0   
2015-08-20 17:00:00                             257.0   
2015-08-20 17:15:00                             257.0   
2015-08-20 17:30:00                             257.0   
2015-08-20 17:45:00                             257.0   

                     (02001) centro comercial santa fe  (02101) toberin  \
timestamp                                                                 
2015-08-15 04:00:00                              254.0            254.0   
2015-08-15 04:15:00                              254.0            254.0   
2015-08-15 04:30:00                              254.0            254.0   
2015-08-15 04:45:00                              255.0            255.0   
2015-08-15 05:00:00                              255.0            255.0   
...                                                ...              ...   
2015-08-20 16:45:00                              257.0            257.0   
2015-08-20 17:00:00                              257.0            257.0   
2015-08-20 17:15:00                              257.0            257.0   
2015-08-20 17:30:00                              257.0            257.0   
2015-08-20 17:45:00                              257.0            257.0   

                     (02102) calle 161  (02103) mazuren  
timestamp                                                
2015-08-15 04:00:00              254.0            254.0  
2015-08-15 04:15:00              254.0            254.0  
2015-08-15 04:30:00              254.0            254.0  
2015-08-15 04:45:00              255.0            255.0  
2015-08-15 05:00:00              255.0            255.0  
...                                ...              ...  
2015-08-20 16:45:00              257.0            257.0  
2015-08-20 17:00:00              257.0            257.0  
2015-08-20 17:15:00              257.0            257.0  
2015-08-20 17:30:00              257.0            257.0  
2015-08-20 17:45:00              257.0            257.0  

[436 rows x 5 columns]

In [23]:
train_data, test_data, metadata = data.tf_data(
        transactions_path = '../../data/transactions.parquet',
        stations_path = '../../data/stations_DB.parquet',
        aggregation = "15-mins",
        train_date = "2015-08-20",
        max_transactions = 1500,
        max_stations  = 5)


Train features shape: (378, 18, 5)
Test features shape: (58, 18, 5)

Train time_embeddings shape: (378, 19, 8)
Test time_embeddings shape: (58, 19, 8)

Train spatial_embeddings shape: (378, 5, 2)
Test spatial_embeddings shape: (58, 5, 2)

Train labels shape: (378, 5)
Test labels shape: (58, 5)



In [26]:
train_data['spatial_embeddings'][0]

<tf.Tensor: shape=(5, 2), dtype=float64, numpy=
array([[-4.40028658, -4.84577421],
       [-4.78932063, -4.95052437],
       [-4.08125421, -4.77791487],
       [-3.87390425, -4.72856262],
       [-3.58816588, -4.66070327]])>

In [4]:
os.chdir('../')
import transformer_model
os.chdir('notebooks')

In [12]:
layer = transformer_model.MinMax()
layer.adapt(train_data['features'])
minmax_normalized = layer(train_data['features'])

In [13]:
layer(minmax_normalized, reverse = True)

<tf.Tensor: shape=(378, 18, 5), dtype=float32, numpy=
array([[[  0.      ,   0.      ,   0.      ,   0.      ,   0.      ],
        [  0.      ,   0.      ,   0.      ,   0.      ,   0.      ],
        [  0.      ,   0.      ,   0.      ,   0.      ,   0.      ],
        ...,
        [328.      ,   0.      ,  72.      ,  38.      ,  17.      ],
        [231.      ,   0.      ,  54.      ,  14.      ,  10.      ],
        [154.      ,   0.      ,  24.      ,  12.      ,   7.      ]],

       [[  0.      ,   0.      ,   0.      ,   0.      ,   0.      ],
        [  0.      ,   0.      ,   0.      ,   0.      ,   0.      ],
        [ 56.      ,   0.      ,   7.      ,   0.      ,   2.      ],
        ...,
        [231.      ,   0.      ,  54.      ,  14.      ,  10.      ],
        [154.      ,   0.      ,  24.      ,  12.      ,   7.      ],
        [  0.      ,   0.      ,   0.      ,   0.      ,   0.      ]],

       [[ 16.      ,   0.      ,   0.      ,   0.      ,   0.      ],
      